// This file re-exports icons from lucide-react to keep icon usage consistent
// and make it easier to swap icons in the future
import {
  Menu as MenuIcon,
  X as XIcon,
  Bell as BellIcon,
  Eye as EyeIcon,
  Edit as EditIcon,
  ArrowUp as ArrowUpIcon,
  ArrowDown as ArrowDownIcon,
  LayoutDashboard as DashboardIcon,
  Download as DownloadIcon,
  Plus as PlusIcon,
  RefreshCw as RefreshIcon,
  MoreHorizontal as MoreHorizontalIcon,
  ShoppingBag as ShoppingBagIcon,
  Store as StoreIcon,
  User as UserIcon,
  Users as UsersIcon,
  Settings as SettingsIcon,
  LogOut as LogOutIcon,
  Search as SearchIcon,
  Filter as FilterIcon,
  Save as SaveIcon,
  Trash as TrashIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronUp as ChevronUpIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  CirclePlus as CirclePlusIcon,
  CircleMinus as CircleMinusIcon,
  Calendar as CalendarIcon,
  Mail as MailIcon,
  FileText as FileTextIcon,
  DollarSign as DollarSignIcon,
  BarChart as BarChartIcon,
  LineChart as LineChartIcon,
  PieChart as PieChartIcon,
  Home as HomeIcon,
  Info as InfoIcon,
  AlertCircle as AlertCircleIcon,
  ExternalLink as ExternalLinkIcon,
  Copy as CopyIcon,
  Clipboard as ClipboardIcon,
  Image as ImageIcon,
  Upload as UploadIcon,
  Package as PackageIcon,
} from "lucide-react";

export {
  MenuIcon,
  XIcon,
  BellIcon,
  EyeIcon,
  EditIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  DashboardIcon,
  DownloadIcon,
  PlusIcon,
  RefreshIcon,
  MoreHorizontalIcon,
  ShoppingBagIcon,
  StoreIcon,
  UserIcon,
  UsersIcon,
  SettingsIcon,
  LogOutIcon,
  SearchIcon,
  FilterIcon,
  SaveIcon,
  TrashIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  CirclePlusIcon,
  CircleMinusIcon,
  CalendarIcon,
  MailIcon,
  FileTextIcon,
  DollarSignIcon,
  BarChartIcon,
  LineChartIcon,
  PieChartIcon,
  HomeIcon,
  InfoIcon,
  AlertCircleIcon,
  ExternalLinkIcon,
  CopyIcon,
  ClipboardIcon,
  ImageIcon,
  UploadIcon,
  PackageIcon,
};
